build:	AP_Server.java Environment.java Map.java Department.java Agent.java
	javac AP_Server.java Environment.java Map.java Department.java Agent.java 

run:	
	java AP_Server

zip:	AP_Server.class Department.class Agent.class Map.class
	jar cfm AP_Server.jar manifest.txt *.class 

launch:	AP_Server.jar
	java -jar AP_Server.jar
	
